Repository toktokhan-tomato/tomatos, pull requests merged in 2024-10, with the labels that each got.

#4 전역 스타일 초기 세팅
  public/fonts/Pretendard-Black.woff
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-ExtraBold.woff
  public/fonts/Pretendard-ExtraLight.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-Thin.woff
  src/app/favicon.ico
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/style/font.css
  src/style/globals.css
  src/style/index.css
  src/style/tailwind.css
  tailwind.config.ts
Labels: design, chore

#8 Feature/#7 husky 세팅
  .husky/pre-commit
  package-lock.json
  package.json
  public/fonts/Pretendard-Black.woff
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-ExtraBold.woff
  public/fonts/Pretendard-ExtraLight.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-Thin.woff
  src/app/favicon.ico
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/style/font.css
  src/style/globals.css
  src/style/index.css
  src/style/tailwind.css
  tailwind.config.ts
Labels: chore

#6 폴더 구조 초기 세팅 #5
  src/assets/index.ts
  src/components/common/Button.tsx
  src/components/common/Card.tsx
  src/components/common/Navbar.tsx
  src/components/contest/Empty.tsx
  src/components/search/Empty.tsx
  src/hooks/empty.ts
  src/types/type.d.ts
Labels: chore

#13 공모전 페이지 필터링 기능 퍼블리싱
  public/fonts/Recipekorea.ttf
  public/images/tomato-stem.svg
  src/app/contest/page.tsx
  src/components/contest/Empty.tsx
  src/components/contest/EventCard.tsx
  src/components/contest/Filter.tsx
  src/components/contest/FilterGroup.tsx
  src/components/contest/FilterOption.tsx
  src/components/contest/FilterReset.tsx
  src/components/contest/ResultCount.tsx
  src/components/contest/SortingOptions.tsx
  src/lib/filterGroups.ts
  src/lib/filterOptions.ts
  src/style/font.css
  tailwind.config.ts
Labels: feat

#14 레이아웃 Nav, Footer 컴포넌트 퍼블리싱
  package-lock.json
  package.json
  src/app/activity/[id]/page.tsx
  src/app/activity/page.tsx
  src/app/page.tsx
  src/assets/images/images.ts
  src/assets/images/music_icon.png
  src/assets/images/search_icon.png
  src/assets/images/sns_icon.png
  src/assets/images/tomato_icon_red.png
  src/assets/images/tomato_icon_yellow.png
  src/assets/images/tomato_logo.png
  src/components/layout/Footer.tsx
  src/components/layout/Navbar.tsx
  src/style/globals.css
  src/style/tailwind.css
  tailwind.config.ts
Labels: design, feat

#16 feat: add Contest detail Page
  package-lock.json
  package.json
  src/app/contest/[id]/page.tsx
  src/assets/images/contest_poster.png
  src/assets/images/images.ts
  src/assets/images/tomato_icon_red_1.png
  src/assets/images/tomato_icon_red_2.png
  src/components/common/DdayTag.tsx
  src/components/layout/Navbar.tsx
  src/style/globals.css
  src/style/tailwind.css
Labels: design, feat

#20 image 에러 수정
  package-lock.json
  public/images/contest_poster.png
  public/images/images.ts
  public/images/music_icon.png
  public/images/search_icon.png
  public/images/sns_icon.png
  public/images/tomato_icon_red_1.png
  public/images/tomato_icon_red_2.png
  public/images/tomato_icon_yellow.png
  public/images/tomato_logo.png
  public/images/tomato_pick_banner.png
  public/images/tomatopick_banner.png
  src/app/contest/[id]/page.tsx
  src/app/contest/_components/DetailInfo.tsx
  src/app/magazine/page.tsx
  src/assets/images/images.ts
  src/assets/index.ts
  src/components/common/DdayTag.tsx
  src/components/common/TabSwitchCase.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Navbar.tsx
  src/components/magazine/MagazineFilter.tsx
  src/components/magazine/MagazineMain.tsx
  src/components/magazine/constents/AwardGallery.tsx
  src/components/magazine/constents/TomatoPick.tsx
  src/components/magazine/constents/TomatoReport.tsx
  src/components/magazine/constents/TomatoTip.tsx
  src/lib/filterGroups.ts
  src/style/globals.css
  src/style/tailwind.css
Labels: fix

#21 feat: update layout css
  src/app/contest/[id]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/style/globals.css
Labels: design

#22 공모전 페이지 퍼블리싱 완료
  public/images/reset_icon.svg
  src/app/contest/[id]/page.tsx
  src/app/contest/page.tsx
  src/components/common/Button.tsx
  src/components/common/Card.tsx
  src/components/common/CardItem.tsx
  src/components/common/CardList.tsx
  src/components/common/EventCard.tsx
  src/components/common/Filter.tsx
  src/components/common/FilterGroup.tsx
  src/components/common/FilterOption.tsx
  src/components/common/FilterReset.tsx
  src/components/common/PageTitle.tsx
  src/components/common/ResultCount.tsx
  src/components/common/SortingOptions.tsx
  src/components/contest/ResultCount.tsx
  src/components/contest/SortingOptions.tsx
  src/types/type.d.ts
Labels: feat
